### ISSUE TITLE
called with wrong argument types  in  split_tab_widget.py

### ISSUE THREAD

**Issue by softminer** [enthought/traitsbackendqt#1]
TypeError: 'PySide.QtCore.QObject.connect' called with wrong argument types:   PySide.QtCore.QObject.connect(NoneType, str, instancemethod) in enthought\pyface\ui\qt4\workbench\split_tab_widget.py in sample  AcmeLab

def **init**(self, *args):
        """ Initialise the instance. """

```
    QtGui.QSplitter.__init__(self, *args)

    self.clear()

    QtCore.QObject.connect(QtGui.qApp,
            QtCore.SIGNAL('focusChanged(QWidget *,QWidget *)'),
            self._focus_changed)
```

**Comment by sjagoe** [comment]
The fix for this is to use "QtGui.QApplication.instance()" instead of QtGui.qApp, which does not seem to work with PySide.

**Comment by softminer** [comment]
or  
 QtCore.QObject.connect(self,
                QtCore.SIGNAL('focusChanged()'),self,
                QtCore.SLOT('_focus_changed()'))
with Pyside？

**Comment by mdickinson** [comment]
This project is no longer maintained. Closing the issue prior to archiving the repository.
